In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer, Binarizer
from sklearn.feature_selection import SelectKBest, f_classif, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from pandas import read_excel

In [ ]:
names1 = ['Call  Failure','Complains,Subscription  Length','Charge  Amount','Seconds of Use','Frequency of use','Frequency of SMS','Distinct Called Numbers','Age Group','Tariff Plan','Status','Age','Customer Value','Churn']
data = pd.read_csv("Customer Churn.csv")

In [ ]:
data.head(10)

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   
5             11          0                    38               1   
6              4          0                    38               0   
7             13          0                    37               2   
8              7          0                    38               0   
9              7          0                    38               1   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   
5            3775                82                32   
6            2360                39               285   
7            9115               121               144   
8           13773               169                 0   
9            4515                83                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   
5                       28          3            1       1   30   
6                       18          3            1       1   30   
7                       43          3            1       1   30   
8                       44          3            1       1   30   
9                       25          3            1       1   30   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0  
5         282.280      0  
6        1235.960      0  
7         945.440      0  
8         557.680      0  
9         191.920      0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Call  Failure            3150 non-null   int64  
 1   Complains                3150 non-null   int64  
 2   Subscription  Length     3150 non-null   int64  
 3   Charge  Amount           3150 non-null   int64  
 4   Seconds of Use           3150 non-null   int64  
 5   Frequency of use         3150 non-null   int64  
 6   Frequency of SMS         3150 non-null   int64  
 7   Distinct Called Numbers  3150 non-null   int64  
 8   Age Group                3150 non-null   int64  
 9   Tariff Plan              3150 non-null   int64  
 10  Status                   3150 non-null   int64  
 11  Age                      3150 non-null   int64  
 12  Customer Value           3150 non-null   float64
 13  Churn                    3150 non-null   int64  
dtypes: float64(1), int64(13)

In [14]:
array = data.values

In [15]:
X = array[:,0:12]
Y = array[:,13]

# Предварительная обработка данных

In [16]:
scaler = MinMaxScaler(feature_range=(0, 1))
conversion = scaler.fit_transform(X)
print(conversion[0:5,:])

[[0.22222222 0.         0.79545455 0.         0.25570509 0.27843137
  0.00957854 0.17525773 0.5        0.         0.         0.375     ]
 [0.         0.         0.81818182 0.         0.01860737 0.01960784
  0.01340996 0.04123711 0.25       0.         1.         0.25      ]
 [0.27777778 0.         0.77272727 0.         0.14353423 0.23529412
  0.68773946 0.24742268 0.5        0.         0.         0.375     ]
 [0.27777778 0.         0.79545455 0.         0.24564073 0.25882353
  0.00191571 0.36082474 0.         0.         0.         0.        ]
 [0.08333333 0.         0.79545455 0.         0.14002341 0.22745098
  0.00383142 0.34020619 0.         0.         0.         0.        ]]


Масштабирование факторных признаков на отрезок [0,1]

In [17]:
scaler2 = StandardScaler().fit(X)
conversion2 = scaler2.transform(X)
print(conversion2[0:5,:])

[[ 0.05122913 -0.2878304   0.63672633 -0.61996205 -0.02441119  0.02681625
  -0.60751272 -0.37815805  0.19494132 -0.29040893 -0.57466206 -0.11307444]
 [-1.05028466 -0.2878304   0.75338358 -0.61996205 -0.98980697 -1.12292553
  -0.58969054 -1.1333308  -0.92561556 -0.29040893  1.74015315 -0.67934551]
 [ 0.32660758 -0.2878304   0.52006909 -0.61996205 -0.48113965 -0.16480738
   2.54701243  0.02847342  0.19494132 -0.29040893 -0.57466206 -0.11307444]
 [ 0.32660758 -0.2878304   0.63672633 -0.61996205 -0.06539048 -0.0602854
  -0.64315707  0.66746575 -2.04617244 -0.29040893 -0.57466206 -1.81188763]
 [-0.63721699 -0.2878304   0.63672633 -0.61996205 -0.49543475 -0.19964804
  -0.63424598  0.55128532 -2.04617244 -0.29040893 -0.57466206 -1.81188763]]


Стандартизация факторных признаков

In [18]:
normalizer = Normalizer().fit(X)
conversion3 = normalizer.transform(X)
print(conversion3[0:5,:])

[[1.83029111e-03 0.00000000e+00 8.69388279e-03 0.00000000e+00
  9.99796521e-01 1.62438336e-02 1.14393195e-03 3.88936862e-03
  6.86359168e-04 2.28786389e-04 2.28786389e-04 6.86359168e-03]
 [0.00000000e+00 0.00000000e+00 1.21302416e-01 0.00000000e+00
  9.89081235e-01 1.55515917e-02 2.17722284e-02 1.24412734e-02
  6.22063670e-03 3.11031835e-03 6.22063670e-03 7.77579587e-02]
 [4.03152202e-03 0.00000000e+00 1.49166315e-02 0.00000000e+00
  9.88932351e-01 2.41891321e-02 1.44731640e-01 9.67565284e-03
  1.20945661e-03 4.03152202e-04 4.03152202e-04 1.20945661e-02]
 [2.38158985e-03 0.00000000e+00 9.05004144e-03 0.00000000e+00
  9.99791420e-01 1.57184930e-02 2.38158985e-04 8.33556448e-03
  2.38158985e-04 2.38158985e-04 2.38158985e-04 3.57238478e-03]
 [1.25298516e-03 0.00000000e+00 1.58711454e-02 0.00000000e+00
  9.99464496e-01 2.42243798e-02 8.35323440e-04 1.37828368e-02
  4.17661720e-04 4.17661720e-04 4.17661720e-04 6.26492580e-03]]


Нормализация факторных признаков

In [19]:
binarizer = Binarizer(threshold=0.0).fit(X)
conversion4 = binarizer.transform(X)
print(conversion4[0:5,:])

[[1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]]


Бинарное кодирование факторных признаков

# Отбор признаков

In [26]:
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)
print(fit.scores_)
features = fit.transform(X)
print(features[0:5,:])

[2.543e-01 1.243e+03 3.347e+00 1.343e+02 3.089e+02 3.190e+02 1.613e+02
 2.655e+02 6.666e-01 3.567e+01 1.044e+03 9.871e-01]
[[0.000e+00 4.370e+03 7.100e+01 1.000e+00]
 [0.000e+00 3.180e+02 5.000e+00 2.000e+00]
 [0.000e+00 2.453e+03 6.000e+01 1.000e+00]
 [0.000e+00 4.198e+03 6.600e+01 1.000e+00]
 [0.000e+00 2.393e+03 5.800e+01 1.000e+00]]


'Status', 'Age', 'Churn' топ 3 значимых признака



In [22]:
model = LogisticRegression(solver='liblinear')
rfe = RFE(model, n_features_to_select=3)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 3
Selected Features: [False  True False False False False False False False  True  True False]
Feature Ranking: [ 4  1  6  2 10  5  9  7  3  1  1  8]


'Subscription  Length', 'Age', ''Status' топ 3 значимых признака

In [23]:
pca = PCA(n_components=3)
fit = pca.fit(X)
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [9.99253774e-01 7.06803857e-04 2.21558084e-05]
[[ 8.67905620e-04 -6.64627174e-06  2.54492900e-04  1.61855598e-04
   9.99908218e-01  1.29438815e-02  2.73211941e-03  2.77459600e-03
   4.26207516e-06  8.52546021e-06 -4.74069407e-05  4.38116111e-05]
 [-4.81422665e-03 -2.41636703e-04  4.93281672e-03  6.24504178e-04
  -2.75645744e-03  1.75900130e-03  9.99939774e-01  1.65308954e-03
  -4.53120501e-04  4.39098931e-04 -9.68892645e-04 -7.59789068e-03]
 [ 1.28921795e-01  5.07786913e-04 -1.23515766e-02 -5.33283515e-03
  -1.29674502e-02  9.11554287e-01 -2.07455003e-03  3.84803142e-01
  -7.17471821e-03  3.35145306e-03 -1.67228110e-03 -6.28909593e-02]]


In [24]:
model = ExtraTreesClassifier(n_estimators=100)
model.fit(X, Y)
print(model.feature_importances_)

[0.06248259 0.22094048 0.10724552 0.01496252 0.1097128  0.10812666
 0.06635428 0.08204412 0.03078423 0.0043333  0.16517332 0.02784017]


'Complains', 'Age', 'Seconds of Use' топ 3 значимых признака